// Mocks generated by Mockito 5.0.5 from annotations
// in stopwatch/test/laps_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:stopwatch/database/table.dart' as _i2;
import 'package:stopwatch/model/history.dart' as _i3;
import 'package:stopwatch/model/lap.dart' as _i6;
import 'package:stopwatch/repository/history_repository.dart' as _i4;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeTable<T> extends _i1.Fake implements _i2.Table<T> {}

class _FakeHistory extends _i1.Fake implements _i3.History {}

/// A class which mocks [HistoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryRepository extends _i1.Mock implements _i4.HistoryRepository {
  MockHistoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Table<_i3.History>> getTable() => (super.noSuchMethod(
          Invocation.method(#getTable, []),
          returnValue:
              Future<_i2.Table<_i3.History>>.value(_FakeTable<_i3.History>()))
      as _i5.Future<_i2.Table<_i3.History>>);
  @override
  _i5.Future<Iterable<_i3.History>> getHistorys() =>
      (super.noSuchMethod(Invocation.method(#getHistorys, []),
              returnValue: Future<Iterable<_i3.History>>.value([]))
          as _i5.Future<Iterable<_i3.History>>);
  @override
  _i5.Future<_i3.History?> getHistory(dynamic key) =>
      (super.noSuchMethod(Invocation.method(#getHistory, [key]),
              returnValue: Future<_i3.History?>.value(_FakeHistory()))
          as _i5.Future<_i3.History?>);
  @override
  _i5.Future<void> deleteHistory(dynamic key) =>
      (super.noSuchMethod(Invocation.method(#deleteHistory, [key]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  bool isCurrentHistory() =>
      (super.noSuchMethod(Invocation.method(#isCurrentHistory, []),
          returnValue: false) as bool);
  @override
  void renewCurrentHistory() =>
      super.noSuchMethod(Invocation.method(#renewCurrentHistory, []),
          returnValueForMissingStub: null);
  @override
  void clearCurrentHistory() =>
      super.noSuchMethod(Invocation.method(#clearCurrentHistory, []),
          returnValueForMissingStub: null);
  @override
  _i5.Future<void> overwriteLapsInCurrentHistory(List<_i6.Lap>? laps) => (super
      .noSuchMethod(Invocation.method(#overwriteLapsInCurrentHistory, [laps]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> overwriteTimesInCurrentHistory(int? msec) => (super
      .noSuchMethod(Invocation.method(#overwriteTimesInCurrentHistory, [msec]),
          returnValue: Future<void>.value(null),
          returnValueForMissingStub: Future.value()) as _i5.Future<void>);
}
